######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 3 12:39:10 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += plot.cpp
